/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * clientView.java
 *
 * Created on Nov 27, 2013, 11:06:54 PM
 */

package client;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Sujon
 */
public class clientView extends javax.swing.JFrame {

    Client cl;
    String clientName="";
    java.io.File file;
    String file_name="";
    HashMap<String,ArrayList<String>>  f_list;
    JList list;
    String  sel_file;
    long fileSize;
    
    /** Creates new form clientView */
    public clientView() {
        initComponents();
    }

    public void setClient(Client x,String na,HashMap<String,ArrayList<String>> ll){
        String[] listData=new String[20];
        cl =x;
        clientName=na;
        f_list=(HashMap<String, ArrayList<String>>) ll.clone();
        int k=0;

        for ( String key : f_list.keySet()){


             listData[k]=key;
             k++;

            }


        list = new JList(listData);
        fileList.setModel(list.getModel());
        welcome.setText("Welcome"+" "+clientName);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_pane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Browse = new javax.swing.JButton();
        Share = new javax.swing.JButton();
        filedirectory = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        filepanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList();
        DownloadButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Browse.setText("Browse");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });

        Share.setText("Share");
        Share.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShareActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("Choose a file to share");

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        welcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcome.setText("Welcome ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Share)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filedirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LogoutButton)
                                    .addComponent(Browse)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoutButton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filedirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Browse))
                .addGap(26, 26, 26)
                .addComponent(Share)
                .addGap(66, 66, 66)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tab_pane.addTab("Share a File", jPanel1);

        fileList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        fileList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        fileList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fileListValueChanged(evt);
            }
        });
        fileList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fileListPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(fileList);

        DownloadButton.setText("Download");
        DownloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("logout");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filepanelLayout = new javax.swing.GroupLayout(filepanel);
        filepanel.setLayout(filepanelLayout);
        filepanelLayout.setHorizontalGroup(
            filepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .addGroup(filepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DownloadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addGap(55, 55, 55))
        );
        filepanelLayout.setVerticalGroup(
            filepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filepanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(filepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DownloadButton)
                    .addComponent(logOutButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tab_pane.addTab("Shared Files", filepanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_pane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        // TODO add your handling code here:
                javax.swing.JFileChooser jfc = new javax.swing.JFileChooser();
        int returnVal = jfc.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
                file = jfc.getSelectedFile();
            }
         file_name=file.getName();

         fileSize=file.length();
        filedirectory.setText(file.toString());

        

    }//GEN-LAST:event_BrowseActionPerformed

    private void ShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShareActionPerformed
        try {
            cl.sendFileName(file_name+" "+clientName+" "+fileSize);

            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(clientView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ShareActionPerformed

    private void fileListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fileListValueChanged


        // TODO add your handling code here:
    }//GEN-LAST:event_fileListValueChanged

    private void fileListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fileListPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fileListPropertyChange

    private void DownloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadButtonActionPerformed

         sel_file= (String) fileList.getSelectedValue();

        try {
            cl.downloadRequest(sel_file, clientName);
        } catch (IOException ex) {
            Logger.getLogger(clientView.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         System.out.println(sel_file);
        // TODO add your handling code here:
    }//GEN-LAST:event_DownloadButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
       
        try {
            cl.closeConnection();
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(clientView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed

                try {
            cl.closeConnection();
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(clientView.class.getName()).log(Level.SEVERE, null, ex);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_logOutButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Browse;
    private javax.swing.JButton DownloadButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton Share;
    private javax.swing.JList fileList;
    private javax.swing.JTextField filedirectory;
    private javax.swing.JPanel filepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JTabbedPane tab_pane;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

}
